In [20]:
import cv2
import numpy as np 
 
# read and scale down image
# wget https://bigsnarf.files.wordpress.com/2017/05/hammer.png
cap = cv2.VideoCapture('forest_fire_youtube.mp4')
#This loop ensures that we read frame by frame, where the frame is just an image from the video. Each image is proccessed 
while(1):
    # cap.read gives you an array, we ignore the first part of the array and assign the second part to the varible frame
    _, frame = cap.read()
    # threshold image
    ret, threshed_img = cv2.threshold(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY), 6, 255, cv2.THRESH_BINARY)

    # find contours and get the external one

    _, contours, hier = cv2.findContours(threshed_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
     
    # with each contour, draw boundingRect in green
    # a minAreaRect in red and
    # a minEnclosingCircle in blue
    for c in contours:

        # get the min area rect
        rect = cv2.minAreaRect(c)
        box = cv2.boxPoints(rect)
        # convert all coordinates floating point values to int
        box = np.int0(box)
        # draw a red 'nghien' rectangle
        cv2.drawContours(frame, [box], 0, (0, 0, 255))


    #cv2.drawContours(img, contours, 3, (255, 255, 0), 1)
    print(len(contours))
    print(box)
    cv2.imshow("contours", frame)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break
        
cv2.destroyAllWindows()
cap.release()

1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  

1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  719]
 [   0  719]
 [   0    0]
 [1279    0]]
1
[[1279  