In [15]:
#Import opencv and numpy (calling them as cv2 and np)
import cv2
import numpy as np
#Import video using opencv and name it as cap
cap = cv2.VideoCapture('forest_fire_youtube.mp4')
#cap = cv2.imread('DJI_0136.jpg')
#This loop ensures that we read frame by frame, where the frame is just an image from the video. Each image is proccessed 
while(1):
    # cap.read gives you an array, we ignore the first part of the array and assign the second part to the varible frame
    _, frame = cap.read()
    # we create the histogram
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # create the range we want 
    lower = np.array([0, 100, 100])
    upper = np.array([50, 255, 255])
    # mask is the image without the pixels that are not in the range we want
    mask = cv2.inRange(hsv, lower, upper)
    # if pixel was removed from varible mask is black, if pixel in mask and frame(original image) is same, then it is replaced with white
    res = cv2.bitwise_and(frame,frame, mask = mask)
    
    # threshold image
    ret, threshed_img = cv2.threshold(cv2.cvtColor(res, cv2.COLOR_BGR2GRAY), 50, 255, cv2.THRESH_BINARY)
    # find contours and get the external one
    _, contours, hier = cv2.findContours(threshed_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    # with each contour, draw boundingRect in gree a minAreaRect in red and a minEnclosingCircle in blue
    for c in contours:

        # get the min area rect
        rect = cv2.minAreaRect(c)
        box = cv2.boxPoints(rect)
        # convert all coordinates floating point values to int
        box = np.int0(box)
        # draw a red 'nghien' rectangle
        cv2.drawContours(frame, [box], 0, (0, 0, 255))
    

    cv2.imshow('Original',frame)
    cv2.imshow('Res[extract black/white]',res)
    #cv2.drawContours(img, contours, 3, (255, 255, 0), 1)
    print(len(contours))
    print(box)
    cv2.imshow("contours", frame)
    #wait 5 miliseconds (not realy sure why, but seems either if u press the key it stops, or it's just a delay)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break


cv2.destroyAllWindows()
cap.release()

86
[[675 529]
 [674 528]
 [674 527]
 [675 528]]
88
[[676 528]
 [673 526]
 [674 525]
 [677 527]]
87
[[673 522]
 [673 522]
 [673 522]
 [673 522]]
92
[[677 532]
 [674 532]
 [674 527]
 [677 527]]
96
[[906 520]
 [906 520]
 [907 520]
 [907 520]]
103
[[893 526]
 [890 526]
 [890 520]
 [893 520]]
108
[[673 529]
 [672 529]
 [672 526]
 [673 526]]
86
[[686 540]
 [668 523]
 [673 517]
 [692 534]]
105
[[666 520]
 [666 520]
 [666 520]
 [666 520]]
106
[[667 519]
 [666 519]
 [666 516]
 [667 516]]
100
[[663 515]
 [660 515]
 [660 512]
 [663 512]]
95
[[660 515]
 [660 515]
 [660 515]
 [660 515]]
95
[[867 511]
 [866 510]
 [866 509]
 [867 510]]
90
[[869 514]
 [869 514]
 [869 515]
 [869 515]]
80
[[867 517]
 [865 517]
 [865 514]
 [867 514]]
95
[[678 533]
 [672 527]
 [674 524]
 [681 531]]
80
[[873 480]
 [873 480]
 [873 480]
 [873 480]]
80
[[677 531]
 [671 531]
 [671 524]
 [677 524]]
81
[[675 531]
 [667 522]
 [669 520]
 [677 529]]
79
[[673 530]
 [665 527]
 [667 521]
 [675 524]]
75
[[672 531]
 [667 526]
 [669 524]

57
[[633 268]
 [633 268]
 [633 268]
 [633 268]]
71
[[635 277]
 [632 277]
 [632 274]
 [635 274]]
63
[[637 275]
 [635 273]
 [637 272]
 [639 274]]
60
[[626 272]
 [626 272]
 [626 275]
 [626 275]]
64
[[628 273]
 [624 271]
 [627 264]
 [631 265]]
58
[[629 261]
 [626 261]
 [626 260]
 [629 260]]
61
[[624 254]
 [624 254]
 [625 254]
 [625 254]]
48
[[630 258]
 [626 255]
 [627 254]
 [631 257]]
49
[[629 255]
 [627 255]
 [627 252]
 [629 252]]
43
[[626 247]
 [624 245]
 [625 244]
 [627 246]]
42
[[618 259]
 [616 259]
 [616 258]
 [618 258]]
42
[[627 280]
 [621 273]
 [624 271]
 [629 278]]
34
[[625 275]
 [622 275]
 [622 271]
 [625 271]]
42
[[621 269]
 [620 269]
 [620 266]
 [621 266]]
42
[[618 260]
 [618 260]
 [618 260]
 [618 260]]
35
[[806 450]
 [806 450]
 [806 450]
 [806 450]]
38
[[804 450]
 [804 450]
 [805 450]
 [805 450]]
37
[[771 466]
 [771 466]
 [771 466]
 [771 466]]
39
[[764 466]
 [764 466]
 [764 466]
 [764 466]]
33
[[762 470]
 [761 468]
 [768 465]
 [769 467]]
33
[[868 454]
 [868 454]
 [868 454]
 [86

48
[[763 434]
 [760 434]
 [760 433]
 [763 433]]
38
[[760 430]
 [760 430]
 [760 430]
 [760 430]]
44
[[763 435]
 [761 434]
 [762 431]
 [764 432]]
36
[[752 432]
 [752 432]
 [752 432]
 [752 432]]
33
[[756 441]
 [749 436]
 [752 431]
 [760 437]]
38
[[751 437]
 [749 432]
 [754 431]
 [756 436]]
46
[[748 426]
 [748 426]
 [748 426]
 [748 426]]
56
[[746 422]
 [746 422]
 [747 422]
 [747 422]]
46
[[741 467]
 [719 461]
 [729 422]
 [751 428]]
53
[[739 432]
 [737 427]
 [745 425]
 [746 430]]
52
[[754 476]
 [715 470]
 [722 426]
 [761 431]]
60
[[604 185]
 [604 185]
 [604 187]
 [604 187]]
49
[[600 191]
 [600 176]
 [609 176]
 [609 191]]
62
[[605 189]
 [594 176]
 [602 170]
 [612 183]]
57
[[615 189]
 [589 178]
 [594 167]
 [619 177]]
67
[[606 191]
 [586 168]
 [598 157]
 [618 180]]
62
[[607 190]
 [584 167]
 [596 155]
 [619 178]]
67
[[602 177]
 [588 177]
 [588 156]
 [602 156]]
55
[[589 156]
 [586 156]
 [586 152]
 [589 152]]
55
[[717 417]
 [717 417]
 [717 417]
 [717 417]]
51
[[712 445]
 [705 444]
 [708 417]
 [71

74
[[511 163]
 [510 163]
 [510 160]
 [511 160]]
79
[[688 379]
 [686 220]
 [739 219]
 [742 378]]
89
[[500 218]
 [500 218]
 [500 218]
 [500 218]]
80
[[517 273]
 [477 236]
 [500 211]
 [540 248]]
82
[[515 269]
 [477 236]
 [498 211]
 [536 245]]
74
[[495 207]
 [494 207]
 [494 206]
 [495 206]]
80
[[686 376]
 [686 210]
 [737 210]
 [737 376]]
80
[[688 376]
 [688 209]
 [737 209]
 [737 376]]
86
[[719 210]
 [719 210]
 [719 210]
 [719 210]]
73
[[731 349]
 [684 343]
 [700 208]
 [747 214]]
78
[[690 347]
 [690 208]
 [735 208]
 [735 347]]
75
[[499 243]
 [485 209]
 [504 201]
 [519 235]]
75
[[498 196]
 [498 196]
 [498 196]
 [498 196]]
89
[[494 192]
 [494 192]
 [494 192]
 [494 192]]
95
[[495 186]
 [495 186]
 [495 186]
 [495 186]]
112
[[499 236]
 [471 190]
 [493 177]
 [520 223]]
108
[[497 234]
 [472 180]
 [494 170]
 [519 224]]
93
[[497 225]
 [475 169]
 [491 163]
 [514 218]]
68
[[512 254]
 [469 167]
 [488 157]
 [532 244]]
92
[[484 161]
 [484 154]
 [487 154]
 [487 161]]
93
[[484 153]
 [484 149]
 [487 149]
 [

110
[[656 237]
 [656 232]
 [665 232]
 [665 237]]
108
[[662 236]
 [660 234]
 [661 233]
 [663 235]]
116
[[664 277]
 [664 237]
 [687 237]
 [687 277]]
107
[[675 280]
 [659 239]
 [679 232]
 [695 273]]
105
[[687 279]
 [664 279]
 [664 240]
 [687 240]]
127
[[687 278]
 [664 278]
 [664 240]
 [687 240]]
118
[[675 281]
 [660 241]
 [678 234]
 [694 274]]
133
[[681 247]
 [677 247]
 [677 240]
 [681 240]]
123
[[674 279]
 [664 238]
 [681 234]
 [691 275]]
123
[[668 236]
 [668 235]
 [671 235]
 [671 236]]
110
[[671 282]
 [665 235]
 [684 233]
 [689 280]]
96
[[670 235]
 [670 235]
 [670 235]
 [670 235]]
106
[[672 240]
 [672 240]
 [672 240]
 [672 240]]
107
[[675 244]
 [672 244]
 [672 240]
 [675 240]]
100
[[672 240]
 [672 240]
 [672 241]
 [672 241]]
98
[[673 247]
 [670 244]
 [674 240]
 [677 243]]
107
[[675 246]
 [670 245]
 [672 239]
 [677 241]]
118
[[666 281]
 [666 242]
 [687 242]
 [687 281]]
88
[[664 281]
 [664 246]
 [687 246]
 [687 281]]
115
[[670 264]
 [662 258]
 [671 244]
 [679 249]]
113
[[678 248]
 [678 24

73
[[688 445]
 [688 445]
 [688 445]
 [688 445]]
81
[[531 442]
 [531 442]
 [531 442]
 [531 442]]
78
[[531 442]
 [531 442]
 [531 442]
 [531 442]]
77
[[687 443]
 [687 443]
 [687 443]
 [687 443]]
68
[[691 459]
 [689 459]
 [689 448]
 [691 448]]
75
[[482 248]
 [482 248]
 [482 251]
 [482 251]]
76
[[482 251]
 [479 249]
 [482 245]
 [484 246]]
81
[[482 251]
 [479 245]
 [482 243]
 [485 249]]
79
[[485 249]
 [482 249]
 [482 242]
 [485 242]]
72
[[658 260]
 [658 260]
 [659 259]
 [659 259]]
72
[[658 260]
 [658 260]
 [658 260]
 [658 260]]
69
[[658 260]
 [658 260]
 [658 260]
 [658 260]]
58
[[682 439]
 [682 439]
 [682 439]
 [682 439]]
64
[[682 439]
 [682 439]
 [683 439]
 [683 439]]
61
[[656 264]
 [656 264]
 [656 264]
 [656 264]]
56
[[654 262]
 [654 262]
 [654 263]
 [654 263]]
60
[[682 452]
 [682 438]
 [683 438]
 [683 452]]
56
[[682 449]
 [682 438]
 [683 438]
 [683 449]]
75
[[652 260]
 [652 257]
 [655 257]
 [655 260]]
68
[[653 260]
 [653 257]
 [655 257]
 [655 260]]
63
[[655 260]
 [653 260]
 [653 258]
 [65

105
[[584 294]
 [584 294]
 [585 294]
 [585 294]]
115
[[582 298]
 [581 294]
 [582 293]
 [583 297]]
102
[[595 294]
 [595 294]
 [595 294]
 [595 294]]
104
[[586 299]
 [584 296]
 [591 293]
 [593 296]]
100
[[592 298]
 [591 296]
 [592 296]
 [593 298]]
112
[[592 296]
 [592 296]
 [593 297]
 [593 297]]
104
[[592 296]
 [592 296]
 [593 296]
 [593 296]]
110
[[590 298]
 [590 298]
 [590 298]
 [590 298]]
122
[[588 298]
 [588 298]
 [588 298]
 [588 298]]
115
[[589 300]
 [589 300]
 [589 300]
 [589 300]]
132
[[587 300]
 [587 300]
 [587 300]
 [587 300]]
116
[[587 314]
 [581 304]
 [584 302]
 [590 312]]
125
[[585 313]
 [578 304]
 [583 301]
 [590 310]]
101
[[591 308]
 [580 305]
 [581 302]
 [591 305]]
97
[[584 313]
 [584 304]
 [589 304]
 [589 313]]
101
[[580 311]
 [580 304]
 [587 304]
 [587 311]]
114
[[582 306]
 [582 306]
 [582 306]
 [582 306]]
110
[[585 306]
 [585 306]
 [585 306]
 [585 306]]
120
[[582 308]
 [582 308]
 [582 308]
 [582 308]]
123
[[585 306]
 [585 306]
 [585 306]
 [585 306]]
122
[[589 321]
 [585 

83
[[542 507]
 [518 483]
 [531 470]
 [555 494]]
79
[[546 504]
 [505 488]
 [513 466]
 [555 482]]
75
[[513 471]
 [512 470]
 [512 469]
 [513 470]]
77
[[541 506]
 [502 488]
 [513 465]
 [551 482]]
80
[[519 314]
 [519 314]
 [519 314]
 [519 314]]
90
[[540 507]
 [503 480]
 [515 463]
 [552 490]]
90
[[503 462]
 [499 459]
 [502 455]
 [506 458]]
93
[[514 330]
 [514 330]
 [515 330]
 [515 330]]
97
[[507 454]
 [506 454]
 [506 450]
 [507 450]]
102
[[509 461]
 [506 461]
 [506 454]
 [509 454]]
91
[[512 469]
 [512 469]
 [513 469]
 [513 469]]
98
[[498 479]
 [498 474]
 [501 474]
 [501 479]]
94
[[505 467]
 [505 467]
 [506 467]
 [506 467]]
88
[[498 470]
 [498 470]
 [499 471]
 [499 471]]
101
[[499 472]
 [498 472]
 [498 470]
 [499 470]]
88
[[498 466]
 [498 466]
 [498 466]
 [498 466]]
93
[[466 436]
 [466 436]
 [467 436]
 [467 436]]
96
[[529 482]
 [529 482]
 [529 482]
 [529 482]]
93
[[466 441]
 [466 441]
 [466 441]
 [466 441]]
92
[[529 515]
 [514 488]
 [542 472]
 [557 499]]
88
[[549 520]
 [510 499]
 [521 479]
 [

113
[[400 408]
 [400 402]
 [405 402]
 [405 408]]
114
[[393 423]
 [384 405]
 [410 392]
 [419 411]]
109
[[391 422]
 [384 399]
 [415 389]
 [422 412]]
100
[[386 421]
 [378 396]
 [425 383]
 [432 407]]
104
[[385 419]
 [379 393]
 [429 381]
 [436 407]]
107
[[380 418]
 [374 391]
 [437 376]
 [443 403]]
117
[[370 411]
 [370 384]
 [443 384]
 [443 411]]
100
[[369 414]
 [363 386]
 [413 375]
 [419 403]]
122
[[370 413]
 [362 384]
 [404 374]
 [411 402]]
121
[[403 389]
 [400 389]
 [400 384]
 [403 384]]
117
[[376 383]
 [376 378]
 [383 378]
 [383 383]]
104
[[410 445]
 [410 445]
 [410 445]
 [410 445]]
102
[[414 447]
 [414 447]
 [415 447]
 [415 447]]
94
[[469 499]
 [458 477]
 [483 464]
 [495 487]]
112
[[408 448]
 [408 448]
 [408 448]
 [408 448]]
112
[[411 443]
 [411 443]
 [411 443]
 [411 443]]
102
[[406 442]
 [406 442]
 [406 442]
 [406 442]]
99
[[413 443]
 [411 443]
 [411 442]
 [413 442]]
103
[[413 442]
 [413 442]
 [413 443]
 [413 443]]
112
[[413 444]
 [411 444]
 [411 442]
 [413 442]]
108
[[417 446]
 [417 4

71
[[574 469]
 [485 466]
 [487 407]
 [576 409]]
64
[[503 406]
 [503 406]
 [505 406]
 [505 406]]
51
[[506 404]
 [506 404]
 [507 405]
 [507 405]]
55
[[584 463]
 [497 460]
 [499 402]
 [586 405]]
71
[[511 401]
 [511 400]
 [513 400]
 [513 401]]
57
[[587 466]
 [503 456]
 [511 390]
 [594 400]]
65
[[592 457]
 [505 454]
 [507 387]
 [594 389]]
62
[[594 455]
 [506 453]
 [508 383]
 [596 384]]
62
[[600 454]
 [512 453]
 [512 377]
 [601 378]]
72
[[602 455]
 [512 450]
 [516 372]
 [606 376]]
67
[[603 452]
 [521 450]
 [523 373]
 [604 375]]
58
[[606 451]
 [523 448]
 [525 377]
 [608 379]]
71
[[605 462]
 [525 447]
 [539 374]
 [619 388]]
53
[[530 447]
 [526 377]
 [597 374]
 [601 443]]
56
[[532 449]
 [532 374]
 [616 374]
 [616 449]]
58
[[565 370]
 [565 370]
 [565 370]
 [565 370]]
45
[[534 453]
 [534 370]
 [623 370]
 [623 453]]
55
[[579 374]
 [579 372]
 [580 372]
 [580 374]]
68
[[628 445]
 [539 442]
 [541 371]
 [630 373]]
63
[[542 443]
 [540 370]
 [629 368]
 [631 441]]
81
[[516 376]
 [514 369]
 [522 367]
 [52

86
[[690 222]
 [670 194]
 [686 181]
 [707 209]]
114
[[684 193]
 [674 189]
 [676 185]
 [686 188]]
113
[[656 213]
 [656 186]
 [701 186]
 [701 213]]
104
[[656 207]
 [656 184]
 [701 184]
 [701 207]]
118
[[658 199]
 [658 176]
 [701 176]
 [701 199]]
131
[[672 193]
 [672 176]
 [701 176]
 [701 193]]
123
[[697 191]
 [678 191]
 [678 174]
 [697 174]]
120
[[675 190]
 [671 176]
 [695 170]
 [698 184]]
122
[[673 189]
 [670 172]
 [696 166]
 [700 183]]
130
[[696 165]
 [696 162]
 [703 162]
 [703 165]]
121
[[700 161]
 [698 158]
 [707 154]
 [709 156]]
119
[[700 157]
 [698 154]
 [708 148]
 [710 152]]
130
[[631 221]
 [631 218]
 [639 218]
 [639 221]]
132
[[665 229]
 [648 229]
 [648 220]
 [665 220]]
106
[[715 241]
 [652 229]
 [657 207]
 [719 220]]
128
[[701 232]
 [662 219]
 [667 204]
 [706 217]]
120
[[699 221]
 [666 214]
 [669 201]
 [701 208]]
130
[[689 217]
 [668 203]
 [674 194]
 [695 208]]
105
[[672 197]
 [672 192]
 [679 192]
 [679 197]]
138
[[676 193]
 [674 190]
 [675 189]
 [677 192]]
131
[[620 260]
 [620 

141
[[663 429]
 [542 379]
 [626 173]
 [748 223]]
122
[[662 428]
 [542 378]
 [635 155]
 [755 205]]
125
[[665 161]
 [650 161]
 [650 146]
 [665 146]]
131
[[652 142]
 [652 142]
 [653 142]
 [653 142]]
115
[[640 167]
 [640 144]
 [663 144]
 [663 167]]
128
[[640 161]
 [640 148]
 [659 148]
 [659 161]]
134
[[641 224]
 [616 192]
 [631 181]
 [655 213]]
122
[[691 230]
 [691 230]
 [691 231]
 [691 231]]
134
[[567 257]
 [561 252]
 [578 229]
 [585 235]]
123
[[579 228]
 [579 228]
 [579 228]
 [579 228]]
117
[[573 253]
 [561 247]
 [569 231]
 [581 237]]
114
[[579 228]
 [579 228]
 [579 228]
 [579 228]]
103
[[579 226]
 [579 226]
 [579 227]
 [579 227]]
101
[[579 225]
 [578 224]
 [578 223]
 [579 224]]
114
[[578 222]
 [578 222]
 [579 222]
 [579 222]]
107
[[680 309]
 [592 302]
 [599 215]
 [687 222]]
114
[[679 307]
 [593 295]
 [604 218]
 [690 231]]
102
[[623 432]
 [533 379]
 [631 213]
 [721 266]]
95
[[630 223]
 [630 210]
 [635 210]
 [635 223]]
113
[[569 234]
 [569 234]
 [569 234]
 [569 234]]
120
[[608 415]
 [534 

153
[[524 447]
 [447 365]
 [578 241]
 [656 324]]
164
[[554 203]
 [554 200]
 [559 200]
 [559 203]]
162
[[545 449]
 [446 402]
 [526 233]
 [625 280]]
161
[[539 451]
 [443 394]
 [539 231]
 [635 287]]
169
[[540 449]
 [441 398]
 [529 227]
 [628 278]]
148
[[533 448]
 [440 388]
 [543 228]
 [636 288]]
156
[[521 449]
 [453 357]
 [599 249]
 [667 341]]
158
[[520 448]
 [451 360]
 [596 247]
 [665 335]]
162
[[530 448]
 [440 389]
 [546 227]
 [636 286]]
158
[[530 448]
 [440 389]
 [547 227]
 [636 287]]
160
[[529 447]
 [440 389]
 [547 227]
 [635 286]]
170
[[563 446]
 [486 430]
 [521 260]
 [597 276]]
162
[[560 446]
 [485 430]
 [522 256]
 [597 272]]
164
[[558 446]
 [484 430]
 [523 248]
 [598 264]]
158
[[551 446]
 [482 427]
 [535 240]
 [604 259]]
164
[[551 450]
 [480 423]
 [550 237]
 [621 264]]
174
[[565 245]
 [558 245]
 [558 240]
 [565 240]]
161
[[565 243]
 [564 243]
 [564 242]
 [565 242]]
163
[[566 242]
 [566 242]
 [566 242]
 [566 242]]
144
[[573 261]
 [563 261]
 [563 258]
 [573 258]]
156
[[573 251]
 [564

140
[[530 239]
 [521 236]
 [522 234]
 [531 237]]
138
[[539 217]
 [536 217]
 [536 216]
 [539 216]]
128
[[537 213]
 [536 213]
 [536 212]
 [537 212]]
101
[[628 289]
 [627 289]
 [627 288]
 [628 288]]
105
[[440 286]
 [440 286]
 [440 286]
 [440 286]]
103
[[424 311]
 [418 292]
 [445 283]
 [451 303]]
112
[[428 278]
 [428 278]
 [428 278]
 [428 278]]
100
[[418 307]
 [418 281]
 [445 281]
 [445 307]]
104
[[437 284]
 [436 282]
 [438 281]
 [439 282]]
91
[[448 307]
 [417 303]
 [420 284]
 [450 288]]
110
[[430 288]
 [428 288]
 [428 286]
 [430 286]]
117
[[427 286]
 [427 286]
 [427 286]
 [427 286]]
103
[[432 291]
 [432 282]
 [445 282]
 [445 291]]
91
[[439 284]
 [439 284]
 [439 285]
 [439 285]]
80
[[435 282]
 [435 282]
 [435 283]
 [435 283]]
75
[[440 330]
 [440 330]
 [440 330]
 [440 330]]
82
[[438 330]
 [438 330]
 [440 330]
 [440 330]]
89
[[354 293]
 [354 293]
 [354 293]
 [354 293]]
76
[[354 288]
 [354 288]
 [354 288]
 [354 288]]
75
[[352 295]
 [352 295]
 [352 295]
 [352 295]]
95
[[355 292]
 [355 292]
 [3